import os
import pandas as pd
from openai import OpenAI
from openai import OpenAIError

def is_ai_configured() -> bool:
    """Check if the AI API key is configured."""
    return bool(os.getenv("GEMINI_API_KEY")) or bool(os.getenv("OPENAI_API_KEY"))

def build_analysis_context(
    df: pd.DataFrame,
    current_j: float,
    current_condition: dict,
    comparison: dict = None
) -> str:
    """
    Build the context string containing verified data generated by the Python application.
    """
    context_lines = []
    
    context_lines.append("CASE:")
    context_lines.append("P4119")
    context_lines.append("")
    
    context_lines.append("AVAILABLE CONDITIONS:")
    j_values = df["J"].tolist()
    context_lines.append(", ".join([f"{j:.3f}" for j in j_values]))
    context_lines.append("")
    
    context_lines.append("CURRENT CONDITION:")
    context_lines.append(f"J = {current_j:.3f}")
    context_lines.append(f"KTP (Blade Thrust) = {current_condition.get('KTP', 'N/A')}")
    context_lines.append(f"KQP (Blade Torque) = {current_condition.get('KQP', 'N/A')}")
    context_lines.append(f"KTH (Hub Thrust) = {current_condition.get('KTH', 'N/A')}")
    context_lines.append(f"KQH (Hub Torque) = {current_condition.get('KQH', 'N/A')}")
    context_lines.append("")
    
    context_lines.append("FULL PERFORMANCE TABLE:")
    context_lines.append(df.to_string(index=False))
    context_lines.append("")
    
    if comparison:
        context_lines.append("USER IS COMPARING TWO CONDITIONS:")
        j_a = comparison["J_baseline"]
        j_b = comparison["J_compared"]
        context_lines.append(f"CONDITION A: J = {j_a:.3f}")
        context_lines.append(f"CONDITION B: J = {j_b:.3f}")
        context_lines.append("DETERMINISTIC COMPARISON RESULTS:")
        for coeff, vals in comparison.get("coefficients", {}).items():
            context_lines.append(f"  {coeff}:")
            context_lines.append(f"    Absolute change: {vals.get('abs_change')}")
            pct_change = vals.get('pct_change')
            pct_str = f"{pct_change:.2f}%" if pct_change is not None else "N/A"
            context_lines.append(f"    Percentage change: {pct_str}")
        context_lines.append("")
        
    return "\n".join(context_lines)

def ask_ai(question: str, context: str) -> str:
    """
    Send the question and context to the AI model for interpretation.
    Handles missing keys and API errors gracefully.
    """
    if not is_ai_configured():
        return "AI assistant is not configured. Set GEMINI_API_KEY to enable AI interpretation."
        
    gemini_key = os.getenv("GEMINI_API_KEY")
    if gemini_key:
        client = OpenAI(
            api_key=gemini_key,
            base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
        )
        model = os.getenv("GEMINI_MODEL", "gemini-1.5-flash")
    else:
        # Fallback to OpenAI if configured
        client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        model = os.getenv("OPENAI_MODEL", "gpt-3.5-turbo")
    
    system_prompt = (
        "You are an engineering analysis assistant for a small PROPAN potential-flow prototype.\n\n"
        "Use only the numerical data supplied in the context.\n"
        "Do not invent simulation results, measurements, physical properties, CFD results, or numerical values.\n"
        "Do not perform hidden numerical calculations when the Python application has already supplied the calculated values.\n"
        "When discussing a change, use the supplied deterministic comparison values.\n"
        "Explain trends clearly and cautiously.\n\n"
        "Distinguish between:\n"
        "- what the PROPAN output directly reports\n"
        "- what can reasonably be interpreted from the supplied trend\n\n"
        "If the supplied data is insufficient to answer a question, say so.\n"
        "Do not claim that the prototype itself is running the full PROPAN solver unless the application explicitly provides solver output.\n"
        "Keep answers concise and engineering-focused."
    )
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Context data:\n{context}\n\nQuestion: {question}"}
    ]
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=0.2, # Keep it deterministic and factual
        )
        return response.choices[0].message.content
    except OpenAIError as e:
        return f"An error occurred while communicating with the AI service: {e}"
